# Generated by Django 4.1.3 on 2022-12-08 09:47

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
                ('SongName', models.CharField(max_length=50)),
                ('ArtistName', models.CharField(max_length=100)),
                ('Created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
