# Generated by Django 4.1.3 on 2022-12-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicvideos',
            name='ArtistImage',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='musicvideos',
            name='IsFeatured',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='musicvideos',
            name='IsTrending',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='musicvideos',
            name='NewRelease',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='musicvideos',
            name='SongNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
