# Generated by Django 4.1.3 on 2022-12-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0003_alter_musicvideos_isfeatured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicvideos',
            name='SongType',
            field=models.CharField(blank=True, choices=[('Bongo Flavor', 'Bongo Flavor'), ('Hip Hop', 'Hip Hop'), ('RNB', 'RNB')], max_length=100, null=True),
        ),
    ]
