# Generated by Django 4.1.3 on 2022-12-11 10:01

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0004_musicvideos_songtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
                ('TutorialName', models.CharField(max_length=50)),
                ('ArtistName', models.CharField(max_length=100)),
                ('IsFeatured', models.BooleanField(blank=True, default=False, null=True)),
                ('IsTrending', models.BooleanField(blank=True, default=False, null=True)),
                ('NewRelease', models.BooleanField(blank=True, default=False, null=True)),
                ('ArtistImage', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('TutorialNumber', models.IntegerField(blank=True, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('TutorialType', models.CharField(blank=True, choices=[('Python Tutorials', 'Python Tutorials'), ('Django Tutorials', 'Django Tutorials'), ('Html & Css Tutorials', 'Html & Css Tutorials'), ('Javascript Tutorials', 'Javascript Tutorials'), ('Bootstrap Tutorials', 'Bootstrap Tutorials')], max_length=100, null=True)),
            ],
        ),
    ]
