# Generated by Django 4.1.3 on 2022-12-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0005_tutorialvideos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicvideos',
            name='ArtistName',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='musicvideos',
            name='SongName',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='musicvideos',
            name='SongType',
            field=models.CharField(blank=True, choices=[('Bongo Flavor', 'Bongo Flavor'), ('Hip Hop', 'Hip Hop'), ('RNB', 'RNB')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tutorialvideos',
            name='ArtistName',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tutorialvideos',
            name='TutorialName',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tutorialvideos',
            name='TutorialType',
            field=models.CharField(blank=True, choices=[('Python Tutorials', 'Python Tutorials'), ('Django Tutorials', 'Django Tutorials'), ('Html & Css Tutorials', 'Html & Css Tutorials'), ('Javascript Tutorials', 'Javascript Tutorials'), ('Bootstrap Tutorials', 'Bootstrap Tutorials')], max_length=1000, null=True),
        ),
    ]
