# Generated by Django 4.1.3 on 2022-12-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0006_alter_musicvideos_artistname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicvideos',
            name='ArtistImage',
            field=models.ImageField(blank=True, default='media/media/me.jpg', null=True, upload_to='media/'),
        ),
    ]
